%
% FILE NAME:    fixFormulasWithFULLR.m
%
% DATE CREATED: 2018-10-16
%     MODIFIED: 2018-10-17
%
% PROGRAMMER:   Hao Wang
%               Department of Biology and Biological Engineering
%               Chalmers University of Technology
%
% PURPOSE: This script is to detect and fix the probelmatic formulas found
%          with "FULLR" and derivated characters  (e.g. "LLLL", "U")
%
% Note: Given that these problmematic formulas were introduced from array
%       structure metAssocHMR2Recon3.mat and actually originated from
%       Recon3Mets2MNX.mat. These files will be systematically modified/
%       corrected by this script.


%% Checking the source of these probablematic formulas

load('Recon3Mets2MNX.mat');  % loads as variable "Recon3D"
Recon3Mets2MNX = Recon3D;
load('Recon3D_301.mat');  % loads as variable "Recon3D"

% find out the changed formulas
ind_diffFormula = find(~strcmp(Recon3D.metFormulas, Recon3Mets2MNX.metFormulas));
fprintf('A total of %u formulas are modifed in array structure Recon3Mets2MNX.\n\n',length(ind_diffFormula));

% create an intermediate cell array for investigation
changedFormulas = cell(length(ind_diffFormula),3);
changedFormulas(:,1) = Recon3D.mets(ind_diffFormula);               %met id
changedFormulas(:,2) = Recon3D.metFormulas(ind_diffFormula);        %before
changedFormulas(:,3) = Recon3Mets2MNX.metFormulas(ind_diffFormula); %after

% Inspection of the content of changedFormulas cell array indicates:
% 1. A total of 744 formulas in Recon3Mets2MNX are different from the original values
% 2. These changes were generated by running the function alphabetizeMetFormulas.m
% 3. Among these changed formulas, 428 originally contain "FULLR" that
% should be replaced with "R"
% 4. The other formulas are changed with reordered elements, and they
% should be just changed back to the original ones



