function prettifiedJSON = prettyJson(rawJSON)
% prettyJson
%   Read in raw JSON text that is generated by encodejson function and
%   usually in one line, then convert to pretty format with proper
%   indentations and line breaks
%
% Input:
%   rawJSON             input char array in JSON format
%
% Output:
%   prettifiedJSON      prettified char array in JSON format
%
% Usage: prettifiedJSON = prettyJson(rawJSON)
%
% Hao Wang, 2019-01-07
%

% handle input 
if isstring(rawJSON)
    % if input is supplied as string
    rawJSON = char(rawJSON);
elseif ~ischar(rawJSON)
    % if input is not supplied as char array
    error('The input data type is Not correct!');
end
jsonStr = rawJSON;


% process input string to pretty JSON format
jsonStr = strrep(jsonStr,'{','{\n\t');         % left  curly  bracket
jsonStr = strrep(jsonStr,'}','\n}\n');         % right curly  bracket
jsonStr = strrep(jsonStr,':[',':[\n\t\t');     % left  square bracket
jsonStr = strrep(jsonStr,'",','",\n\t\t');     % internal elements in array
jsonStr = strrep(jsonStr,'"],','"],\n\t');     % last element in array
jsonStr = compose(jsonStr);                    % translate escape-characters

prettifiedJSON = jsonStr{1};                   % convert from cell to char

end

