name: Test metabolic tasks

on: [push]

jobs:
  check-metabolictasks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        task-type: [essential, verification]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r code/test/requirements.txt

      - name: Check ${{ matrix.task-type }} metabolic tasks
        run: python code/test/testMetabolicTasks.py ${{ matrix.task-type }}
