name: Run macaw tests

on: [push, pull_request]

jobs:
  macaw-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install macaw
        run: pip install git+https://github.com/Devlin-Moyer/macaw.git@main numpy==1.26.4

      - name: Run macaw
        run: python code/modelTests/macawTests.py

      - name: Rename output file
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: mv macaw_dead_end_and_duplicate_test_results.csv data/macaw_result_PR$PR_NUMBER.csv

      - name: Auto-commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: memote-bot
          commit_message: "chore: add macaw test result"
          file_pattern: history_report.html
          branch: gh-pages
          repository: gh-pages-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}